name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+2
  file_picker: ^5.1.0
  cloudinary_public: ^0.12.0
  flutter_rating_bar: ^4.0.1
  pay: ^1.0.11
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  flutter_launcher_icons: ^0.10.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: true
  image_path: "assets/icon.png"

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json
